artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: https://drive.google.com/file/d/1wEHylWJRt6xTGati2pufZzWUMV8_WdoL/view?usp=sharing
    local_data_file: artifacts/data_ingestion/kidney-ct-scan-image.zip  # Renamed here
    unzip_dir: artifacts/data_ingestion/kidney-ct-scan-image  # Updated to match the new folder name

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

training:
    root_dir: artifacts/training
    trained_model_path: artifacts/training/model.h5
    training_data: artifacts/data_ingestion/kidney-ct-scan-image/